const express = require('express')
const route = express.Router()
const {getHodCourse,createCourse,getStudentRegCourse,deleteCourse,updateUserCourse,getStafsInfo,updateStafsInfo,stuinfo} = require('../Controllers/CourseController')
const HodrequireAuth = require('../middleware/HodRequireAuth')
route.use(HodrequireAuth)
route.get('/RegStudent/:id',getStudentRegCourse)
route.get('/course',getHodCourse)
route.get('/Stafs',getStafsInfo)
route.post('/studinfo',stuinfo)
route.post('/create',createCourse)
route.put('/update/:id',updateUserCourse)
route.put('/update/staf/:id',updateStafsInfo)
route.delete('/delete/:id',deleteCourse)
module.exports = route