const express = require('express')
const route = express.Router()
const StaffRequireAuth = require('../middleware/StaffRequireAuth')
const {getRegStudents,getStudentInfo,updateStudentInfo,createAttendence,getDate,getAttendenceInfo,getAttendenceDate,StudentAttendence, StudentMarks1,StudentMarks2,StudentMarks3, updateStaffExamInfo} = require('../Controllers/CourseController')
route.use(StaffRequireAuth)
route.get('/RegStudent/:id',getRegStudents)
route.get('/Attendence/:id',getStudentInfo)
route.get('/Date/:id',getDate)
route.post('/Attendence/Given/:id',updateStudentInfo)
route.post('/Attendence/Given',createAttendence)
route.post('/Attendence/student/given/:id',StudentAttendence)
route.post('/Marks/given/CAE1/:id',StudentMarks1)
route.post('/Marks/given/CAE2/:id',StudentMarks2)
route.post('/Marks/given/SEM/:id',StudentMarks3)
route.post('/Marks/given/staffinfo/:id',updateStaffExamInfo)
route.post('/Attendence/Info',getAttendenceInfo)
route.post('/Attendence/Date',getAttendenceDate)
module.exports = route